//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.28 at 12:18:06 PM PST
//

package de.martin_loetzsch.dotml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for arrow-type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="arrow-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="normal"/&gt;
 *     &lt;enumeration value="inv"/&gt;
 *     &lt;enumeration value="dot"/&gt;
 *     &lt;enumeration value="invdot"/&gt;
 *     &lt;enumeration value="odot"/&gt;
 *     &lt;enumeration value="invodot"/&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="tee"/&gt;
 *     &lt;enumeration value="empty"/&gt;
 *     &lt;enumeration value="invempty"/&gt;
 *     &lt;enumeration value="diamond"/&gt;
 *     &lt;enumeration value="odiamond"/&gt;
 *     &lt;enumeration value="box"/&gt;
 *     &lt;enumeration value="obox"/&gt;
 *     &lt;enumeration value="open"/&gt;
 *     &lt;enumeration value="crow"/&gt;
 *     &lt;enumeration value="halfopen"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "arrow-type")
@XmlEnum
public enum ArrowType {

  @XmlEnumValue("normal")
  NORMAL("normal"), @XmlEnumValue("inv")
  INV("inv"), @XmlEnumValue("dot")
  DOT("dot"), @XmlEnumValue("invdot")
  INVDOT("invdot"), @XmlEnumValue("odot")
  ODOT("odot"), @XmlEnumValue("invodot")
  INVODOT("invodot"), @XmlEnumValue("none")
  NONE("none"), @XmlEnumValue("tee")
  TEE("tee"), @XmlEnumValue("empty")
  EMPTY("empty"), @XmlEnumValue("invempty")
  INVEMPTY("invempty"), @XmlEnumValue("diamond")
  DIAMOND("diamond"), @XmlEnumValue("odiamond")
  ODIAMOND("odiamond"), @XmlEnumValue("box")
  BOX("box"), @XmlEnumValue("obox")
  OBOX("obox"), @XmlEnumValue("open")
  OPEN("open"), @XmlEnumValue("crow")
  CROW("crow"), @XmlEnumValue("halfopen")
  HALFOPEN("halfopen");
  private final String value;

  ArrowType(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static ArrowType fromValue(String v) {
    for (ArrowType c : ArrowType.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
