//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.24 at 01:59:12 PM PST
//

package org.apache.camel.schema.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for jibxDataFormat complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jibxDataFormat">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}dataFormat">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="unmarshallClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bindingName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jibxDataFormat")
public class JibxDataFormat extends DataFormat {

  @XmlAttribute(name = "unmarshallClass")
  protected String unmarshallClass;
  @XmlAttribute(name = "bindingName")
  protected String bindingName;

  /**
   * Gets the value of the unmarshallClass property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getUnmarshallClass() {
    return unmarshallClass;
  }

  /**
   * Sets the value of the unmarshallClass property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setUnmarshallClass(String value) {
    this.unmarshallClass = value;
  }

  /**
   * Gets the value of the bindingName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getBindingName() {
    return bindingName;
  }

  /**
   * Sets the value of the bindingName property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setBindingName(String value) {
    this.bindingName = value;
  }

  public JibxDataFormat withUnmarshallClass(String value) {
    setUnmarshallClass(value);
    return this;
  }

  public JibxDataFormat withBindingName(String value) {
    setBindingName(value);
    return this;
  }

  @Override
  public JibxDataFormat withId(String value) {
    setId(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
