//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.03.04 at 01:11:38 AM PST
//

package org.apache.camel.schema.spring;

import java.util.Collection;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for samplingDefinition complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="samplingDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}output">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="samplePeriod" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="messageFrequency" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samplingDefinition")
public class SamplingDefinition extends Output {

  @XmlAttribute(name = "samplePeriod")
  protected Long samplePeriod;
  @XmlAttribute(name = "messageFrequency")
  protected Long messageFrequency;
  @XmlAttribute(name = "units")
  protected String units;

  /**
   * Gets the value of the samplePeriod property.
   * 
   * @return possible object is {@link Long }
   * 
   */
  public Long getSamplePeriod() {
    return samplePeriod;
  }

  /**
   * Sets the value of the samplePeriod property.
   * 
   * @param value allowed object is {@link Long }
   * 
   */
  public void setSamplePeriod(Long value) {
    this.samplePeriod = value;
  }

  /**
   * Gets the value of the messageFrequency property.
   * 
   * @return possible object is {@link Long }
   * 
   */
  public Long getMessageFrequency() {
    return messageFrequency;
  }

  /**
   * Sets the value of the messageFrequency property.
   * 
   * @param value allowed object is {@link Long }
   * 
   */
  public void setMessageFrequency(Long value) {
    this.messageFrequency = value;
  }

  /**
   * Gets the value of the units property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getUnits() {
    return units;
  }

  /**
   * Sets the value of the units property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setUnits(String value) {
    this.units = value;
  }

  public SamplingDefinition withSamplePeriod(Long value) {
    setSamplePeriod(value);
    return this;
  }

  public SamplingDefinition withMessageFrequency(Long value) {
    setMessageFrequency(value);
    return this;
  }

  public SamplingDefinition withUnits(String value) {
    setUnits(value);
    return this;
  }

  @Override
  public SamplingDefinition withAopOrAggregateOrBean(ProcessorDefinition... values) {
    if (values != null) {
      for (ProcessorDefinition value : values) {
        getAopOrAggregateOrBean().add(value);
      }
    }
    return this;
  }

  @Override
  public SamplingDefinition withAopOrAggregateOrBean(Collection<ProcessorDefinition> values) {
    if (values != null) {
      getAopOrAggregateOrBean().addAll(values);
    }
    return this;
  }

  @Override
  public SamplingDefinition withInheritErrorHandler(Boolean value) {
    setInheritErrorHandler(value);
    return this;
  }

  @Override
  public SamplingDefinition withDescription(DescriptionElement value) {
    setDescription(value);
    return this;
  }

  @Override
  public SamplingDefinition withCustomId(Boolean value) {
    setCustomId(value);
    return this;
  }

  @Override
  public SamplingDefinition withId(String value) {
    setId(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
