//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.24 at 01:59:12 PM PST
//

package org.apache.camel.schema.spring;

import java.util.Collection;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for validateDefinition complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="validateDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}noOutputExpressionNode">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validateDefinition")
public class ValidateDefinition extends NoOutputExpressionNode {

  @Override
  public ValidateDefinition withExpressionDefinition(Expression value) {
    setExpressionDefinition(value);
    return this;
  }

  @Override
  public ValidateDefinition withConstant(ConstantExpression value) {
    setConstant(value);
    return this;
  }

  @Override
  public ValidateDefinition withEl(ElExpression value) {
    setEl(value);
    return this;
  }

  @Override
  public ValidateDefinition withGroovy(GroovyExpression value) {
    setGroovy(value);
    return this;
  }

  @Override
  public ValidateDefinition withHeader(HeaderExpression value) {
    setHeader(value);
    return this;
  }

  @Override
  public ValidateDefinition withJxpath(JxPathExpression value) {
    setJxpath(value);
    return this;
  }

  @Override
  public ValidateDefinition withJavaScript(JavaScriptExpression value) {
    setJavaScript(value);
    return this;
  }

  @Override
  public ValidateDefinition withJsonpath(JsonPathExpression value) {
    setJsonpath(value);
    return this;
  }

  @Override
  public ValidateDefinition withLanguage(LanguageExpression value) {
    setLanguage(value);
    return this;
  }

  @Override
  public ValidateDefinition withMethod(MethodCallExpression value) {
    setMethod(value);
    return this;
  }

  @Override
  public ValidateDefinition withMvel(MvelExpression value) {
    setMvel(value);
    return this;
  }

  @Override
  public ValidateDefinition withOgnl(OgnlExpression value) {
    setOgnl(value);
    return this;
  }

  @Override
  public ValidateDefinition withPhp(PhpExpression value) {
    setPhp(value);
    return this;
  }

  @Override
  public ValidateDefinition withProperty(Object value) {
    setProperty(value);
    return this;
  }

  @Override
  public ValidateDefinition withPython(PythonExpression value) {
    setPython(value);
    return this;
  }

  @Override
  public ValidateDefinition withRef(RefExpression value) {
    setRef(value);
    return this;
  }

  @Override
  public ValidateDefinition withRuby(RubyExpression value) {
    setRuby(value);
    return this;
  }

  @Override
  public ValidateDefinition withSimple(SimpleExpression value) {
    setSimple(value);
    return this;
  }

  @Override
  public ValidateDefinition withSpel(SpELExpression value) {
    setSpel(value);
    return this;
  }

  @Override
  public ValidateDefinition withSql(SqlExpression value) {
    setSql(value);
    return this;
  }

  @Override
  public ValidateDefinition withTokenize(TokenizerExpression value) {
    setTokenize(value);
    return this;
  }

  @Override
  public ValidateDefinition withVtdxml(VtdXmlExpression value) {
    setVtdxml(value);
    return this;
  }

  @Override
  public ValidateDefinition withXtokenize(XmlTokenizerExpression value) {
    setXtokenize(value);
    return this;
  }

  @Override
  public ValidateDefinition withXpath(XPathExpression value) {
    setXpath(value);
    return this;
  }

  @Override
  public ValidateDefinition withXquery(XQueryExpression value) {
    setXquery(value);
    return this;
  }

  @Override
  public ValidateDefinition withAopOrAggregateOrBean(ProcessorDefinition... values) {
    if (values != null) {
      for (ProcessorDefinition value : values) {
        getAopOrAggregateOrBean().add(value);
      }
    }
    return this;
  }

  @Override
  public ValidateDefinition withAopOrAggregateOrBean(Collection<ProcessorDefinition> values) {
    if (values != null) {
      getAopOrAggregateOrBean().addAll(values);
    }
    return this;
  }

  @Override
  public ValidateDefinition withInheritErrorHandler(Boolean value) {
    setInheritErrorHandler(value);
    return this;
  }

  @Override
  public ValidateDefinition withDescription(DescriptionDefinition value) {
    setDescription(value);
    return this;
  }

  @Override
  public ValidateDefinition withCustomId(Boolean value) {
    setCustomId(value);
    return this;
  }

  @Override
  public ValidateDefinition withId(String value) {
    setId(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
