//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.03.04 at 01:11:38 AM PST
//

package org.apache.camel.schema.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for weightedLoadBalancerDefinition complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="weightedLoadBalancerDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}loadBalancer">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="roundRobin" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="distributionRatio" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="distributionRatioDelimiter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "weightedLoadBalancerDefinition")
public class WeightedLoadBalancerDefinition extends LoadBalancer {

  @XmlAttribute(name = "roundRobin")
  protected Boolean roundRobin;
  @XmlAttribute(name = "distributionRatio", required = true)
  protected String distributionRatio;
  @XmlAttribute(name = "distributionRatioDelimiter")
  protected String distributionRatioDelimiter;

  /**
   * Gets the value of the roundRobin property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isRoundRobin() {
    return roundRobin;
  }

  /**
   * Sets the value of the roundRobin property.
   * 
   * @param value allowed object is {@link Boolean }
   * 
   */
  public void setRoundRobin(Boolean value) {
    this.roundRobin = value;
  }

  /**
   * Gets the value of the distributionRatio property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDistributionRatio() {
    return distributionRatio;
  }

  /**
   * Sets the value of the distributionRatio property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setDistributionRatio(String value) {
    this.distributionRatio = value;
  }

  /**
   * Gets the value of the distributionRatioDelimiter property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDistributionRatioDelimiter() {
    return distributionRatioDelimiter;
  }

  /**
   * Sets the value of the distributionRatioDelimiter property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setDistributionRatioDelimiter(String value) {
    this.distributionRatioDelimiter = value;
  }

  public WeightedLoadBalancerDefinition withRoundRobin(Boolean value) {
    setRoundRobin(value);
    return this;
  }

  public WeightedLoadBalancerDefinition withDistributionRatio(String value) {
    setDistributionRatio(value);
    return this;
  }

  public WeightedLoadBalancerDefinition withDistributionRatioDelimiter(String value) {
    setDistributionRatioDelimiter(value);
    return this;
  }

  @Override
  public WeightedLoadBalancerDefinition withId(String value) {
    setId(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
