//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.24 at 01:59:12 PM PST
//

package org.apache.camel.schema.spring;

import java.util.Collection;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for whenDefinition complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="whenDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}expressionNode">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "whenDefinition")
@XmlSeeAlso({WhenSkipSendToEndpointDefinition.class})
public class WhenDefinition extends ExpressionNode {

  @Override
  public WhenDefinition withExpressionDefinition(Expression value) {
    setExpressionDefinition(value);
    return this;
  }

  @Override
  public WhenDefinition withConstant(ConstantExpression value) {
    setConstant(value);
    return this;
  }

  @Override
  public WhenDefinition withEl(ElExpression value) {
    setEl(value);
    return this;
  }

  @Override
  public WhenDefinition withGroovy(GroovyExpression value) {
    setGroovy(value);
    return this;
  }

  @Override
  public WhenDefinition withHeader(HeaderExpression value) {
    setHeader(value);
    return this;
  }

  @Override
  public WhenDefinition withJxpath(JxPathExpression value) {
    setJxpath(value);
    return this;
  }

  @Override
  public WhenDefinition withJavaScript(JavaScriptExpression value) {
    setJavaScript(value);
    return this;
  }

  @Override
  public WhenDefinition withJsonpath(JsonPathExpression value) {
    setJsonpath(value);
    return this;
  }

  @Override
  public WhenDefinition withLanguage(LanguageExpression value) {
    setLanguage(value);
    return this;
  }

  @Override
  public WhenDefinition withMethod(MethodCallExpression value) {
    setMethod(value);
    return this;
  }

  @Override
  public WhenDefinition withMvel(MvelExpression value) {
    setMvel(value);
    return this;
  }

  @Override
  public WhenDefinition withOgnl(OgnlExpression value) {
    setOgnl(value);
    return this;
  }

  @Override
  public WhenDefinition withPhp(PhpExpression value) {
    setPhp(value);
    return this;
  }

  @Override
  public WhenDefinition withProperty(Object value) {
    setProperty(value);
    return this;
  }

  @Override
  public WhenDefinition withPython(PythonExpression value) {
    setPython(value);
    return this;
  }

  @Override
  public WhenDefinition withRef(RefExpression value) {
    setRef(value);
    return this;
  }

  @Override
  public WhenDefinition withRuby(RubyExpression value) {
    setRuby(value);
    return this;
  }

  @Override
  public WhenDefinition withSimple(SimpleExpression value) {
    setSimple(value);
    return this;
  }

  @Override
  public WhenDefinition withSpel(SpELExpression value) {
    setSpel(value);
    return this;
  }

  @Override
  public WhenDefinition withSql(SqlExpression value) {
    setSql(value);
    return this;
  }

  @Override
  public WhenDefinition withTokenize(TokenizerExpression value) {
    setTokenize(value);
    return this;
  }

  @Override
  public WhenDefinition withVtdxml(VtdXmlExpression value) {
    setVtdxml(value);
    return this;
  }

  @Override
  public WhenDefinition withXtokenize(XmlTokenizerExpression value) {
    setXtokenize(value);
    return this;
  }

  @Override
  public WhenDefinition withXpath(XPathExpression value) {
    setXpath(value);
    return this;
  }

  @Override
  public WhenDefinition withXquery(XQueryExpression value) {
    setXquery(value);
    return this;
  }

  @Override
  public WhenDefinition withAopOrAggregateOrBean(ProcessorDefinition... values) {
    if (values != null) {
      for (ProcessorDefinition value : values) {
        getAopOrAggregateOrBean().add(value);
      }
    }
    return this;
  }

  @Override
  public WhenDefinition withAopOrAggregateOrBean(Collection<ProcessorDefinition> values) {
    if (values != null) {
      getAopOrAggregateOrBean().addAll(values);
    }
    return this;
  }

  @Override
  public WhenDefinition withInheritErrorHandler(Boolean value) {
    setInheritErrorHandler(value);
    return this;
  }

  @Override
  public WhenDefinition withDescription(DescriptionDefinition value) {
    setDescription(value);
    return this;
  }

  @Override
  public WhenDefinition withCustomId(Boolean value) {
    setCustomId(value);
    return this;
  }

  @Override
  public WhenDefinition withId(String value) {
    setId(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
