//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140310.1920 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 10:26:44 AM PDT 
//


package org.springframework.schema.beans;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.springframework.org/schema/beans}arg-type"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="replacer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "argType"
})
@XmlRootElement(name = "replaced-method")
public class ReplacedMethodElement {

    @XmlElement(name = "arg-type")
    protected List<ArgTypeElement> argType;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "replacer")
    protected String replacer;

    /**
     * Gets the value of the argType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the argType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArgType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArgTypeElement }
     * 
     * 
     */
    public List<ArgTypeElement> getArgType() {
        if (argType == null) {
            argType = new ArrayList<ArgTypeElement>();
        }
        return this.argType;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the replacer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplacer() {
        return replacer;
    }

    /**
     * Sets the value of the replacer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplacer(String value) {
        this.replacer = value;
    }

    public ReplacedMethodElement withArgType(ArgTypeElement... values) {
        if (values!= null) {
            for (ArgTypeElement value: values) {
                getArgType().add(value);
            }
        }
        return this;
    }

    public ReplacedMethodElement withArgType(Collection<ArgTypeElement> values) {
        if (values!= null) {
            getArgType().addAll(values);
        }
        return this;
    }

    public ReplacedMethodElement withName(String value) {
        setName(value);
        return this;
    }

    public ReplacedMethodElement withReplacer(String value) {
        setReplacer(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
    }

}
