//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.04 at 10:47:31 AM PST
//

package com.microsoft.schemas.visio._2006.extension;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for NamedRow_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NamedRow_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NameU" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Del" type="{http://schemas.microsoft.com/visio/2006/extension}ISOBoolean" />
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NamedRow_Type")
@XmlSeeAlso({UserType.class, SmartTagDefType.class, PropType.class, HyperlinkType.class})
public class NamedRowType {

  @XmlAttribute(name = "Name")
  protected String name;
  @XmlAttribute(name = "NameU")
  protected String nameU;
  @XmlAttribute(name = "Del")
  protected BigInteger del;
  @XmlAttribute(name = "ID")
  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger id;

  /**
   * Gets the value of the name property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the nameU property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getNameU() {
    return nameU;
  }

  /**
   * Sets the value of the nameU property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setNameU(String value) {
    this.nameU = value;
  }

  /**
   * Gets the value of the del property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getDel() {
    return del;
  }

  /**
   * Sets the value of the del property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setDel(BigInteger value) {
    this.del = value;
  }

  /**
   * Gets the value of the id property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getID() {
    return id;
  }

  /**
   * Sets the value of the id property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setID(BigInteger value) {
    this.id = value;
  }

  public NamedRowType withName(String value) {
    setName(value);
    return this;
  }

  public NamedRowType withNameU(String value) {
    setNameU(value);
    return this;
  }

  public NamedRowType withDel(BigInteger value) {
    setDel(value);
    return this;
  }

  public NamedRowType withID(BigInteger value) {
    setID(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
