//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.28 at 12:18:04 PM PST
//

package oasis.names.tc.xacml._3_0.core.schema.wd_17;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;

/**
 * <p>
 * Java class for PolicyCombinerParametersType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyCombinerParametersType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:oasis:names:tc:xacml:3.0:core:schema:wd-17}CombinerParametersType"&gt;
 *       &lt;attribute name="PolicyIdRef" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyCombinerParametersType")
public class PolicyCombinerParametersType extends CombinerParametersType implements Cloneable {

  @XmlAttribute(name = "PolicyIdRef", required = true)
  @XmlSchemaType(name = "anyURI")
  protected String policyIdRef;

  /**
   * Gets the value of the policyIdRef property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getPolicyIdRef() {
    return policyIdRef;
  }

  /**
   * Sets the value of the policyIdRef property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  protected void setPolicyIdRef(String value) {
    this.policyIdRef = value;
  }

  public static PolicyCombinerParametersType.Builder<Void> builder() {
    return new PolicyCombinerParametersType.Builder<Void>(null, null, false);
  }

  public static PolicyCombinerParametersType.Builder<Void> copyOf(
      final PolicyCombinerParametersType other) {
    return new PolicyCombinerParametersType.Builder<Void>(null, other, true);
  }

  public static PolicyCombinerParametersType.Builder<Void> copyOf(
      final PolicyCombinerParametersType other, final PropertyTree propertyTree,
      final PropertyTreeUse propertyTreeUse) {
    return new PolicyCombinerParametersType.Builder<Void>(null, other, true, propertyTree,
        propertyTreeUse);
  }

  public static PolicyCombinerParametersType.Builder<Void> copyExcept(
      final PolicyCombinerParametersType other, final PropertyTree propertyTree) {
    return copyOf(other, propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static PolicyCombinerParametersType.Builder<Void> copyOnly(
      final PolicyCombinerParametersType other, final PropertyTree propertyTree) {
    return copyOf(other, propertyTree, PropertyTreeUse.INCLUDE);
  }

  @Override
  public String toString() {
    return (((super.toString() + "(policyIdRef = ") + policyIdRef) + ") ");
  }

  @Override
  public PolicyCombinerParametersType clone() throws CloneNotSupportedException {
    final PolicyCombinerParametersType newObject = ((PolicyCombinerParametersType) super.clone());
    return newObject;
  }

  public static class Builder<TParentBuilder> extends
      CombinerParametersType.Builder<TParentBuilder> {

    private String policyIdRef;

    public Builder(final TParentBuilder parentBuilder, final PolicyCombinerParametersType other,
        final boolean copy) {
      super(parentBuilder, other, copy);
      if (copy) {
        this.policyIdRef = other.policyIdRef;
      }
    }

    public Builder(final TParentBuilder parentBuilder, final PolicyCombinerParametersType other,
        final boolean copy, final PropertyTree propertyTree, final PropertyTreeUse treeUse) {
      super(parentBuilder, other, copy);
      if (copy) {
        final PropertyTree policyIdRefPropertyTree =
            ((propertyTree == null) ? null : propertyTree.get("policyIdRef"));
        if (((treeUse == PropertyTreeUse.INCLUDE) ? (policyIdRefPropertyTree != null)
            : ((policyIdRefPropertyTree == null) || (!policyIdRefPropertyTree.isLeaf())))) {
          this.policyIdRef = other.policyIdRef;
        }
      }
    }

    protected <P extends PolicyCombinerParametersType> P init(final P product) {
      product.policyIdRef = this.policyIdRef;
      return super.init(product);
    }

    public PolicyCombinerParametersType.Builder<TParentBuilder> withPolicyIdRef(
        final String policyIdRef) {
      this.policyIdRef = policyIdRef;
      return this;
    }

    @Override
    public PolicyCombinerParametersType.Builder<TParentBuilder> addCombinerParameter(
        final List<? extends CombinerParameterType> combinerParameter) {
      super.addCombinerParameter(combinerParameter);
      return this;
    }

    @Override
    public PolicyCombinerParametersType.Builder<TParentBuilder> addCombinerParameter(
        CombinerParameterType... combinerParameter) {
      super.addCombinerParameter(combinerParameter);
      return this;
    }

    @Override
    public PolicyCombinerParametersType.Builder<TParentBuilder> withCombinerParameter(
        final List<? extends CombinerParameterType> combinerParameter) {
      super.withCombinerParameter(combinerParameter);
      return this;
    }

    @Override
    public PolicyCombinerParametersType.Builder<TParentBuilder> withCombinerParameter(
        CombinerParameterType... combinerParameter) {
      super.withCombinerParameter(combinerParameter);
      return this;
    }

    @Override
    public CombinerParameterType.Builder<? extends PolicyCombinerParametersType.Builder<TParentBuilder>> addCombinerParameter() {
      return ((CombinerParameterType.Builder<? extends PolicyCombinerParametersType.Builder<TParentBuilder>>) super
          .addCombinerParameter());
    }

    public PolicyCombinerParametersType build() {
      if (this._product == null) {
        return this.init(new PolicyCombinerParametersType());
      } else {
        return ((PolicyCombinerParametersType) this._product);
      }
    }

  }

  public static class Select extends
      PolicyCombinerParametersType.Selector<PolicyCombinerParametersType.Select, Void> {

    Select() {
      super(null, null, null);
    }

    public static PolicyCombinerParametersType.Select _root() {
      return new PolicyCombinerParametersType.Select();
    }

  }

  public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
      extends CombinerParametersType.Selector<TRoot, TParent> {

    private com.kscs.util.jaxb.Selector<TRoot, PolicyCombinerParametersType.Selector<TRoot, TParent>> policyIdRef =
        null;

    public Selector(final TRoot root, final TParent parent, final String propertyName) {
      super(root, parent, propertyName);
    }

    @Override
    public Map<String, PropertyTree> buildChildren() {
      final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
      products.putAll(super.buildChildren());
      if (this.policyIdRef != null) {
        products.put("policyIdRef", this.policyIdRef.init());
      }
      return products;
    }

    public com.kscs.util.jaxb.Selector<TRoot, PolicyCombinerParametersType.Selector<TRoot, TParent>> policyIdRef() {
      return ((this.policyIdRef == null)
          ? this.policyIdRef =
              new com.kscs.util.jaxb.Selector<TRoot, PolicyCombinerParametersType.Selector<TRoot, TParent>>(
                  this._root, this, "policyIdRef") : this.policyIdRef);
    }

  }

}
