//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.27 at 09:43:08 PM PST
//

package de.martin_loetzsch.dotml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * Represents a single node in the graph.
 * 
 * <p>
 * Java class for node complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="node">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.martin-loetzsch.de/DOTML}node-and-record-attributes"/>
 *       &lt;attribute name="fixedsize" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="id" use="required" type="{http://www.martin-loetzsch.de/DOTML}id" />
 *       &lt;attribute name="label" type="{http://www.martin-loetzsch.de/DOTML}label" />
 *       &lt;attribute name="shape" type="{http://www.martin-loetzsch.de/DOTML}shape" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "node")
public class Node {

  @XmlAttribute(name = "fixedsize")
  protected Boolean fixedsize;
  @XmlAttribute(name = "id", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String id;
  @XmlAttribute(name = "label")
  protected String label;
  @XmlAttribute(name = "shape")
  protected Shape shape;
  @XmlAttribute(name = "color")
  protected String color;
  @XmlAttribute(name = "fillcolor")
  protected String fillcolor;
  @XmlAttribute(name = "height")
  protected BigDecimal height;
  @XmlAttribute(name = "style")
  protected Style style;
  @XmlAttribute(name = "width")
  protected BigDecimal width;
  @XmlAttribute(name = "fontname")
  protected String fontname;
  @XmlAttribute(name = "fontsize")
  protected BigDecimal fontsize;
  @XmlAttribute(name = "fontcolor")
  protected String fontcolor;

  /**
   * Gets the value of the fixedsize property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isFixedsize() {
    return fixedsize;
  }

  /**
   * Sets the value of the fixedsize property.
   * 
   * @param value allowed object is {@link Boolean }
   * 
   */
  public void setFixedsize(Boolean value) {
    this.fixedsize = value;
  }

  /**
   * Gets the value of the id property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the label property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getLabel() {
    return label;
  }

  /**
   * Sets the value of the label property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setLabel(String value) {
    this.label = value;
  }

  /**
   * Gets the value of the shape property.
   * 
   * @return possible object is {@link Shape }
   * 
   */
  public Shape getShape() {
    return shape;
  }

  /**
   * Sets the value of the shape property.
   * 
   * @param value allowed object is {@link Shape }
   * 
   */
  public void setShape(Shape value) {
    this.shape = value;
  }

  /**
   * Gets the value of the color property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getColor() {
    return color;
  }

  /**
   * Sets the value of the color property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setColor(String value) {
    this.color = value;
  }

  /**
   * Gets the value of the fillcolor property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFillcolor() {
    return fillcolor;
  }

  /**
   * Sets the value of the fillcolor property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setFillcolor(String value) {
    this.fillcolor = value;
  }

  /**
   * Gets the value of the height property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getHeight() {
    return height;
  }

  /**
   * Sets the value of the height property.
   * 
   * @param value allowed object is {@link BigDecimal }
   * 
   */
  public void setHeight(BigDecimal value) {
    this.height = value;
  }

  /**
   * Gets the value of the style property.
   * 
   * @return possible object is {@link Style }
   * 
   */
  public Style getStyle() {
    return style;
  }

  /**
   * Sets the value of the style property.
   * 
   * @param value allowed object is {@link Style }
   * 
   */
  public void setStyle(Style value) {
    this.style = value;
  }

  /**
   * Gets the value of the width property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getWidth() {
    return width;
  }

  /**
   * Sets the value of the width property.
   * 
   * @param value allowed object is {@link BigDecimal }
   * 
   */
  public void setWidth(BigDecimal value) {
    this.width = value;
  }

  /**
   * Gets the value of the fontname property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFontname() {
    return fontname;
  }

  /**
   * Sets the value of the fontname property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setFontname(String value) {
    this.fontname = value;
  }

  /**
   * Gets the value of the fontsize property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getFontsize() {
    return fontsize;
  }

  /**
   * Sets the value of the fontsize property.
   * 
   * @param value allowed object is {@link BigDecimal }
   * 
   */
  public void setFontsize(BigDecimal value) {
    this.fontsize = value;
  }

  /**
   * Gets the value of the fontcolor property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFontcolor() {
    return fontcolor;
  }

  /**
   * Sets the value of the fontcolor property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setFontcolor(String value) {
    this.fontcolor = value;
  }

  public Node withFixedsize(Boolean value) {
    setFixedsize(value);
    return this;
  }

  public Node withId(String value) {
    setId(value);
    return this;
  }

  public Node withLabel(String value) {
    setLabel(value);
    return this;
  }

  public Node withShape(Shape value) {
    setShape(value);
    return this;
  }

  public Node withColor(String value) {
    setColor(value);
    return this;
  }

  public Node withFillcolor(String value) {
    setFillcolor(value);
    return this;
  }

  public Node withHeight(BigDecimal value) {
    setHeight(value);
    return this;
  }

  public Node withStyle(Style value) {
    setStyle(value);
    return this;
  }

  public Node withWidth(BigDecimal value) {
    setWidth(value);
    return this;
  }

  public Node withFontname(String value) {
    setFontname(value);
    return this;
  }

  public Node withFontsize(BigDecimal value) {
    setFontsize(value);
    return this;
  }

  public Node withFontcolor(String value) {
    setFontcolor(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
