//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.04 at 04:25:41 AM PST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.martin-loetzsch.de/DOTML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.martin_loetzsch.dotml;

