//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.04 at 10:47:31 AM PST
//

package com.microsoft.schemas.visio._2006.extension;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for SmartTagDef_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SmartTagDef_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/visio/2006/extension}NamedRow_Type">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="X" type="{http://schemas.microsoft.com/visio/2006/extension}X_Type" minOccurs="0"/>
 *         &lt;element name="Y" type="{http://schemas.microsoft.com/visio/2006/extension}Y_Type" minOccurs="0"/>
 *         &lt;element name="TagName" type="{http://schemas.microsoft.com/visio/2006/extension}TagName_Type" minOccurs="0"/>
 *         &lt;element name="XJustify" type="{http://schemas.microsoft.com/visio/2006/extension}XJustify_Type" minOccurs="0"/>
 *         &lt;element name="YJustify" type="{http://schemas.microsoft.com/visio/2006/extension}YJustify_Type" minOccurs="0"/>
 *         &lt;element name="DisplayMode" type="{http://schemas.microsoft.com/visio/2006/extension}DisplayMode_Type" minOccurs="0"/>
 *         &lt;element name="ButtonFace" type="{http://schemas.microsoft.com/visio/2006/extension}ButtonFace_Type" minOccurs="0"/>
 *         &lt;element name="Disabled" type="{http://schemas.microsoft.com/visio/2006/extension}Disabled_Type" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://schemas.microsoft.com/visio/2006/extension}Description_Type" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SmartTagDef_Type", propOrder = {"xOrYOrTagName"})
public class SmartTagDefType extends NamedRowType {

  @XmlElements({
      @XmlElement(name = "X", type = XType.class), @XmlElement(name = "Y", type = YType.class),
      @XmlElement(name = "TagName", type = TagNameType.class),
      @XmlElement(name = "XJustify", type = XJustifyType.class),
      @XmlElement(name = "YJustify", type = YJustifyType.class),
      @XmlElement(name = "DisplayMode", type = DisplayModeType.class),
      @XmlElement(name = "ButtonFace", type = ButtonFaceType.class),
      @XmlElement(name = "Disabled", type = DisabledType.class),
      @XmlElement(name = "Description", type = DescriptionType.class)})
  protected List<CellType> xOrYOrTagName;

  /**
   * Gets the value of the xOrYOrTagName property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the xOrYOrTagName property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getXOrYOrTagName().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link XType } {@link YType } {@link TagNameType }
   * {@link XJustifyType } {@link YJustifyType } {@link DisplayModeType } {@link ButtonFaceType } {@link DisabledType }
   * {@link DescriptionType }
   * 
   * 
   */
  public List<CellType> getXOrYOrTagName() {
    if (xOrYOrTagName == null) {
      xOrYOrTagName = new ArrayList<CellType>();
    }
    return this.xOrYOrTagName;
  }

  public SmartTagDefType withXOrYOrTagName(CellType... values) {
    if (values != null) {
      for (CellType value : values) {
        getXOrYOrTagName().add(value);
      }
    }
    return this;
  }

  public SmartTagDefType withXOrYOrTagName(Collection<CellType> values) {
    if (values != null) {
      getXOrYOrTagName().addAll(values);
    }
    return this;
  }

  @Override
  public SmartTagDefType withName(String value) {
    setName(value);
    return this;
  }

  @Override
  public SmartTagDefType withNameU(String value) {
    setNameU(value);
    return this;
  }

  @Override
  public SmartTagDefType withDel(BigInteger value) {
    setDel(value);
    return this;
  }

  @Override
  public SmartTagDefType withID(BigInteger value) {
    setID(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
