//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.04 at 10:47:31 AM PST
//

package com.microsoft.schemas.visio._2006.extension;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for TextCell_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextCell_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="cp" type="{http://schemas.microsoft.com/visio/2006/extension}cp_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pp" type="{http://schemas.microsoft.com/visio/2006/extension}pp_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tp" type="{http://schemas.microsoft.com/visio/2006/extension}tp_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fld" type="{http://schemas.microsoft.com/visio/2006/extension}fld_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextCell_Type", propOrder = {"content"})
@XmlSeeAlso({TextType.class})
public class TextCellType {

  @XmlElementRefs({
      @XmlElementRef(name = "fld", namespace = "http://schemas.microsoft.com/visio/2006/extension", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "pp", namespace = "http://schemas.microsoft.com/visio/2006/extension", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "cp", namespace = "http://schemas.microsoft.com/visio/2006/extension", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "tp", namespace = "http://schemas.microsoft.com/visio/2006/extension", type = JAXBElement.class, required = false)})
  @XmlMixed
  protected List<Serializable> content;

  /**
   * Gets the value of the content property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the content property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getContent().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link String } {@link JAXBElement }{@code <}{@link FldType }
   * {@code >} {@link JAXBElement }{@code <}{@link CpType }{@code >} {@link JAXBElement }{@code <}{@link PpType }{@code >}
   * {@link JAXBElement }{@code <}{@link TpType }{@code >}
   * 
   * 
   */
  public List<Serializable> getContent() {
    if (content == null) {
      content = new ArrayList<Serializable>();
    }
    return this.content;
  }

  public TextCellType withContent(Serializable... values) {
    if (values != null) {
      for (Serializable value : values) {
        getContent().add(value);
      }
    }
    return this;
  }

  public TextCellType withContent(Collection<Serializable> values) {
    if (values != null) {
      getContent().addAll(values);
    }
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
