//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.03.04 at 01:11:38 AM PST
//

package org.apache.camel.schema.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for keyManagersParametersFactoryBean complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="keyManagersParametersFactoryBean">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}abstractKeyManagersParametersFactoryBean">
 *       &lt;sequence>
 *         &lt;element name="keyStore" type="{http://camel.apache.org/schema/spring}keyStoreParametersFactoryBean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "keyManagersParametersFactoryBean", propOrder = {"keyStore"})
public class KeyManagersParametersFactoryBean extends AbstractKeyManagersParametersFactoryBean {

  protected KeyStoreParametersFactoryBean keyStore;

  /**
   * Gets the value of the keyStore property.
   * 
   * @return possible object is {@link KeyStoreParametersFactoryBean }
   * 
   */
  public KeyStoreParametersFactoryBean getKeyStore() {
    return keyStore;
  }

  /**
   * Sets the value of the keyStore property.
   * 
   * @param value allowed object is {@link KeyStoreParametersFactoryBean }
   * 
   */
  public void setKeyStore(KeyStoreParametersFactoryBean value) {
    this.keyStore = value;
  }

  public KeyManagersParametersFactoryBean withKeyStore(KeyStoreParametersFactoryBean value) {
    setKeyStore(value);
    return this;
  }

  @Override
  public KeyManagersParametersFactoryBean withKeyPassword(String value) {
    setKeyPassword(value);
    return this;
  }

  @Override
  public KeyManagersParametersFactoryBean withProvider(String value) {
    setProvider(value);
    return this;
  }

  @Override
  public KeyManagersParametersFactoryBean withAlgorithm(String value) {
    setAlgorithm(value);
    return this;
  }

  @Override
  public KeyManagersParametersFactoryBean withCamelContextId(String value) {
    setCamelContextId(value);
    return this;
  }

  @Override
  public KeyManagersParametersFactoryBean withId(String value) {
    setId(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
