//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140310.1920 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.24 at 02:18:22 PM PDT 
//


package org.apache.camel.schema.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}noOutputDefinition">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="consumes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="produces" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bindingMode" type="{http://camel.apache.org/schema/spring}restBindingMode" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="outType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="skipBindingOnErrorCode" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="enableCORS" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "restBinding")
public class RestBindingElement
    extends NoOutputDefinition
{

    @XmlAttribute(name = "consumes")
    protected String consumes;
    @XmlAttribute(name = "produces")
    protected String produces;
    @XmlAttribute(name = "bindingMode")
    protected RestBindingMode bindingMode;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "outType")
    protected String outType;
    @XmlAttribute(name = "skipBindingOnErrorCode")
    protected Boolean skipBindingOnErrorCode;
    @XmlAttribute(name = "enableCORS")
    protected Boolean enableCORS;

    /**
     * Gets the value of the consumes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumes() {
        return consumes;
    }

    /**
     * Sets the value of the consumes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumes(String value) {
        this.consumes = value;
    }

    /**
     * Gets the value of the produces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduces() {
        return produces;
    }

    /**
     * Sets the value of the produces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduces(String value) {
        this.produces = value;
    }

    /**
     * Gets the value of the bindingMode property.
     * 
     * @return
     *     possible object is
     *     {@link RestBindingMode }
     *     
     */
    public RestBindingMode getBindingMode() {
        return bindingMode;
    }

    /**
     * Sets the value of the bindingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestBindingMode }
     *     
     */
    public void setBindingMode(RestBindingMode value) {
        this.bindingMode = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the outType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutType() {
        return outType;
    }

    /**
     * Sets the value of the outType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutType(String value) {
        this.outType = value;
    }

    /**
     * Gets the value of the skipBindingOnErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSkipBindingOnErrorCode() {
        return skipBindingOnErrorCode;
    }

    /**
     * Sets the value of the skipBindingOnErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSkipBindingOnErrorCode(Boolean value) {
        this.skipBindingOnErrorCode = value;
    }

    /**
     * Gets the value of the enableCORS property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableCORS() {
        return enableCORS;
    }

    /**
     * Sets the value of the enableCORS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableCORS(Boolean value) {
        this.enableCORS = value;
    }

    public RestBindingElement withConsumes(String value) {
        setConsumes(value);
        return this;
    }

    public RestBindingElement withProduces(String value) {
        setProduces(value);
        return this;
    }

    public RestBindingElement withBindingMode(RestBindingMode value) {
        setBindingMode(value);
        return this;
    }

    public RestBindingElement withType(String value) {
        setType(value);
        return this;
    }

    public RestBindingElement withOutType(String value) {
        setOutType(value);
        return this;
    }

    public RestBindingElement withSkipBindingOnErrorCode(Boolean value) {
        setSkipBindingOnErrorCode(value);
        return this;
    }

    public RestBindingElement withEnableCORS(Boolean value) {
        setEnableCORS(value);
        return this;
    }

    @Override
    public RestBindingElement withInheritErrorHandler(Boolean value) {
        setInheritErrorHandler(value);
        return this;
    }

    @Override
    public RestBindingElement withDescription(DescriptionElement value) {
        setDescription(value);
        return this;
    }

    @Override
    public RestBindingElement withCustomId(Boolean value) {
        setCustomId(value);
        return this;
    }

    @Override
    public RestBindingElement withId(String value) {
        setId(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
    }

}
