//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.04 at 10:47:30 AM PST
//

package com.microsoft.schemas.visio._2003.core;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for DocumentSettings_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentSettings_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="GlueSettings" type="{http://schemas.microsoft.com/visio/2003/core}GlueSettings_Type" minOccurs="0"/>
 *         &lt;element name="SnapSettings" type="{http://schemas.microsoft.com/visio/2003/core}SnapSettings_Type" minOccurs="0"/>
 *         &lt;element name="SnapExtensions" type="{http://schemas.microsoft.com/visio/2003/core}SnapExtensions_Type" minOccurs="0"/>
 *         &lt;element name="SnapAngles" type="{http://schemas.microsoft.com/visio/2003/core}SnapAngles_Type" minOccurs="0"/>
 *         &lt;element name="DynamicGridEnabled" type="{http://schemas.microsoft.com/visio/2003/core}DynamicGridEnabled_Type" minOccurs="0"/>
 *         &lt;element name="ProtectStyles" type="{http://schemas.microsoft.com/visio/2003/core}ProtectStyles_Type" minOccurs="0"/>
 *         &lt;element name="ProtectShapes" type="{http://schemas.microsoft.com/visio/2003/core}ProtectShapes_Type" minOccurs="0"/>
 *         &lt;element name="ProtectMasters" type="{http://schemas.microsoft.com/visio/2003/core}ProtectMasters_Type" minOccurs="0"/>
 *         &lt;element name="ProtectBkgnds" type="{http://schemas.microsoft.com/visio/2003/core}ProtectBkgnds_Type" minOccurs="0"/>
 *         &lt;element name="CustomMenusFile" type="{http://schemas.microsoft.com/visio/2003/core}CustomMenusFile_Type" minOccurs="0"/>
 *         &lt;element name="CustomToolbarsFile" type="{http://schemas.microsoft.com/visio/2003/core}CustomToolbarsFile_Type" minOccurs="0"/>
 *         &lt;element name="AttachedToolbars" type="{http://schemas.microsoft.com/visio/2003/core}AttachedToolbars_Type" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="TopPage" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="DefaultTextStyle" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="DefaultLineStyle" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="DefaultFillStyle" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="DefaultGuideStyle" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentSettings_Type", propOrder = {"glueSettingsOrSnapSettingsOrSnapExtensions"})
public class DocumentSettingsType {

  @XmlElements({
      @XmlElement(name = "GlueSettings", type = GlueSettingsType.class),
      @XmlElement(name = "SnapSettings", type = SnapSettingsType.class),
      @XmlElement(name = "SnapExtensions", type = SnapExtensionsType.class),
      @XmlElement(name = "SnapAngles", type = SnapAnglesType.class),
      @XmlElement(name = "DynamicGridEnabled", type = DynamicGridEnabledType.class),
      @XmlElement(name = "ProtectStyles", type = ProtectStylesType.class),
      @XmlElement(name = "ProtectShapes", type = ProtectShapesType.class),
      @XmlElement(name = "ProtectMasters", type = ProtectMastersType.class),
      @XmlElement(name = "ProtectBkgnds", type = ProtectBkgndsType.class),
      @XmlElement(name = "CustomMenusFile", type = CustomMenusFileType.class),
      @XmlElement(name = "CustomToolbarsFile", type = CustomToolbarsFileType.class),
      @XmlElement(name = "AttachedToolbars", type = AttachedToolbarsType.class)})
  protected List<Object> glueSettingsOrSnapSettingsOrSnapExtensions;
  @XmlAttribute(name = "TopPage")
  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger topPage;
  @XmlAttribute(name = "DefaultTextStyle")
  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger defaultTextStyle;
  @XmlAttribute(name = "DefaultLineStyle")
  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger defaultLineStyle;
  @XmlAttribute(name = "DefaultFillStyle")
  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger defaultFillStyle;
  @XmlAttribute(name = "DefaultGuideStyle")
  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger defaultGuideStyle;

  /**
   * Gets the value of the glueSettingsOrSnapSettingsOrSnapExtensions property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the glueSettingsOrSnapSettingsOrSnapExtensions property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getGlueSettingsOrSnapSettingsOrSnapExtensions().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link GlueSettingsType } {@link SnapSettingsType }
   * {@link SnapExtensionsType } {@link SnapAnglesType } {@link DynamicGridEnabledType } {@link ProtectStylesType }
   * {@link ProtectShapesType } {@link ProtectMastersType } {@link ProtectBkgndsType } {@link CustomMenusFileType }
   * {@link CustomToolbarsFileType } {@link AttachedToolbarsType }
   * 
   * 
   */
  public List<Object> getGlueSettingsOrSnapSettingsOrSnapExtensions() {
    if (glueSettingsOrSnapSettingsOrSnapExtensions == null) {
      glueSettingsOrSnapSettingsOrSnapExtensions = new ArrayList<Object>();
    }
    return this.glueSettingsOrSnapSettingsOrSnapExtensions;
  }

  /**
   * Gets the value of the topPage property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getTopPage() {
    return topPage;
  }

  /**
   * Sets the value of the topPage property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setTopPage(BigInteger value) {
    this.topPage = value;
  }

  /**
   * Gets the value of the defaultTextStyle property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getDefaultTextStyle() {
    return defaultTextStyle;
  }

  /**
   * Sets the value of the defaultTextStyle property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setDefaultTextStyle(BigInteger value) {
    this.defaultTextStyle = value;
  }

  /**
   * Gets the value of the defaultLineStyle property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getDefaultLineStyle() {
    return defaultLineStyle;
  }

  /**
   * Sets the value of the defaultLineStyle property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setDefaultLineStyle(BigInteger value) {
    this.defaultLineStyle = value;
  }

  /**
   * Gets the value of the defaultFillStyle property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getDefaultFillStyle() {
    return defaultFillStyle;
  }

  /**
   * Sets the value of the defaultFillStyle property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setDefaultFillStyle(BigInteger value) {
    this.defaultFillStyle = value;
  }

  /**
   * Gets the value of the defaultGuideStyle property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getDefaultGuideStyle() {
    return defaultGuideStyle;
  }

  /**
   * Sets the value of the defaultGuideStyle property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setDefaultGuideStyle(BigInteger value) {
    this.defaultGuideStyle = value;
  }

  public DocumentSettingsType withGlueSettingsOrSnapSettingsOrSnapExtensions(Object... values) {
    if (values != null) {
      for (Object value : values) {
        getGlueSettingsOrSnapSettingsOrSnapExtensions().add(value);
      }
    }
    return this;
  }

  public DocumentSettingsType withGlueSettingsOrSnapSettingsOrSnapExtensions(
      Collection<Object> values) {
    if (values != null) {
      getGlueSettingsOrSnapSettingsOrSnapExtensions().addAll(values);
    }
    return this;
  }

  public DocumentSettingsType withTopPage(BigInteger value) {
    setTopPage(value);
    return this;
  }

  public DocumentSettingsType withDefaultTextStyle(BigInteger value) {
    setDefaultTextStyle(value);
    return this;
  }

  public DocumentSettingsType withDefaultLineStyle(BigInteger value) {
    setDefaultLineStyle(value);
    return this;
  }

  public DocumentSettingsType withDefaultFillStyle(BigInteger value) {
    setDefaultFillStyle(value);
    return this;
  }

  public DocumentSettingsType withDefaultGuideStyle(BigInteger value) {
    setDefaultGuideStyle(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
