//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.04 at 10:47:30 AM PST
//

package com.microsoft.schemas.visio._2003.core;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for Masters_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Masters_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Master" type="{http://schemas.microsoft.com/visio/2003/core}Master_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MasterShortcut" type="{http://schemas.microsoft.com/visio/2003/core}MasterShortcut_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Masters_Type", propOrder = {"master", "masterShortcut"})
public class MastersType {

  @XmlElement(name = "Master")
  protected List<MasterType> master;
  @XmlElement(name = "MasterShortcut")
  protected List<MasterShortcutType> masterShortcut;

  /**
   * Gets the value of the master property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the master property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getMaster().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link MasterType }
   * 
   * 
   */
  public List<MasterType> getMaster() {
    if (master == null) {
      master = new ArrayList<MasterType>();
    }
    return this.master;
  }

  /**
   * Gets the value of the masterShortcut property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the masterShortcut property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getMasterShortcut().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link MasterShortcutType }
   * 
   * 
   */
  public List<MasterShortcutType> getMasterShortcut() {
    if (masterShortcut == null) {
      masterShortcut = new ArrayList<MasterShortcutType>();
    }
    return this.masterShortcut;
  }

  public MastersType withMaster(MasterType... values) {
    if (values != null) {
      for (MasterType value : values) {
        getMaster().add(value);
      }
    }
    return this;
  }

  public MastersType withMaster(Collection<MasterType> values) {
    if (values != null) {
      getMaster().addAll(values);
    }
    return this;
  }

  public MastersType withMasterShortcut(MasterShortcutType... values) {
    if (values != null) {
      for (MasterShortcutType value : values) {
        getMasterShortcut().add(value);
      }
    }
    return this;
  }

  public MastersType withMasterShortcut(Collection<MasterShortcutType> values) {
    if (values != null) {
      getMasterShortcut().addAll(values);
    }
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
