//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.10-b140310.1920
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.04 at 10:47:30 AM PST
//

package com.microsoft.schemas.visio._2003.core;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;

/**
 * <p>
 * Java class for TextBlock_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextBlock_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/visio/2003/core}Row_Type">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="LeftMargin" type="{http://schemas.microsoft.com/visio/2003/core}LeftMargin_Type" minOccurs="0"/>
 *         &lt;element name="RightMargin" type="{http://schemas.microsoft.com/visio/2003/core}RightMargin_Type" minOccurs="0"/>
 *         &lt;element name="TopMargin" type="{http://schemas.microsoft.com/visio/2003/core}TopMargin_Type" minOccurs="0"/>
 *         &lt;element name="BottomMargin" type="{http://schemas.microsoft.com/visio/2003/core}BottomMargin_Type" minOccurs="0"/>
 *         &lt;element name="VerticalAlign" type="{http://schemas.microsoft.com/visio/2003/core}VerticalAlign_Type" minOccurs="0"/>
 *         &lt;element name="TextBkgnd" type="{http://schemas.microsoft.com/visio/2003/core}TextBkgnd_Type" minOccurs="0"/>
 *         &lt;element name="DefaultTabStop" type="{http://schemas.microsoft.com/visio/2003/core}DefaultTabStop_Type" minOccurs="0"/>
 *         &lt;element name="TextDirection" type="{http://schemas.microsoft.com/visio/2003/core}TextDirection_Type" minOccurs="0"/>
 *         &lt;element name="TextBkgndTrans" type="{http://schemas.microsoft.com/visio/2003/core}TextBkgndTrans_Type" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextBlock_Type", propOrder = {"leftMarginOrRightMarginOrTopMargin"})
public class TextBlockType extends RowType {

  @XmlElements({
      @XmlElement(name = "LeftMargin", type = LeftMarginType.class),
      @XmlElement(name = "RightMargin", type = RightMarginType.class),
      @XmlElement(name = "TopMargin", type = TopMarginType.class),
      @XmlElement(name = "BottomMargin", type = BottomMarginType.class),
      @XmlElement(name = "VerticalAlign", type = VerticalAlignType.class),
      @XmlElement(name = "TextBkgnd", type = TextBkgndType.class),
      @XmlElement(name = "DefaultTabStop", type = DefaultTabStopType.class),
      @XmlElement(name = "TextDirection", type = TextDirectionType.class),
      @XmlElement(name = "TextBkgndTrans", type = TextBkgndTransType.class)})
  protected List<CellType> leftMarginOrRightMarginOrTopMargin;

  /**
   * Gets the value of the leftMarginOrRightMarginOrTopMargin property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the leftMarginOrRightMarginOrTopMargin property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getLeftMarginOrRightMarginOrTopMargin().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link LeftMarginType } {@link RightMarginType }
   * {@link TopMarginType } {@link BottomMarginType } {@link VerticalAlignType } {@link TextBkgndType }
   * {@link DefaultTabStopType } {@link TextDirectionType } {@link TextBkgndTransType }
   * 
   * 
   */
  public List<CellType> getLeftMarginOrRightMarginOrTopMargin() {
    if (leftMarginOrRightMarginOrTopMargin == null) {
      leftMarginOrRightMarginOrTopMargin = new ArrayList<CellType>();
    }
    return this.leftMarginOrRightMarginOrTopMargin;
  }

  public TextBlockType withLeftMarginOrRightMarginOrTopMargin(CellType... values) {
    if (values != null) {
      for (CellType value : values) {
        getLeftMarginOrRightMarginOrTopMargin().add(value);
      }
    }
    return this;
  }

  public TextBlockType withLeftMarginOrRightMarginOrTopMargin(Collection<CellType> values) {
    if (values != null) {
      getLeftMarginOrRightMarginOrTopMargin().addAll(values);
    }
    return this;
  }

  @Override
  public TextBlockType withDel(BigInteger value) {
    setDel(value);
    return this;
  }

  /**
   * Generates a String representation of the contents of this type. This is an extension method, produced by the 'ts'
   * xjc plugin
   * 
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
  }

}
